#ifndef PROJECT3_TEST_CONFIG_FUNCTIONS_HPP
#define PROJECT3_TEST_CONFIG_FUNCTIONS_HPP

#define TRICAT(x, y, z) CAT(XCAT(x, y), z)
#define CAT(x, y) XCAT(x, y)
#define XCAT(x, y) x ## y

#define EXPAND(...) __VA_ARGS__
#define PEXPAND(pack) EXPAND pack
#define EAT(...)

#define PP_NUMERAL(num) CAT(PP_NUMERAL, num)

#define RESCAN(arg) CAT(RESCAN_, PP_NUMERAL(COMPILER_RESCAN_COUNT))(arg)
#define RESCAN_N(arg, count) CAT(RESCAN_, PP_NUMERAL(count))(arg)
#define RESCAN_NIL(arg) arg
#define RESCAN_I(arg)   RESCAN_NIL(RESCAN_NIL(RESCAN_NIL(RESCAN_NIL(arg))))
#define RESCAN_II(arg)  RESCAN_I(RESCAN_I(RESCAN_I(RESCAN_I(arg))))
#define RESCAN_III(arg) RESCAN_II(RESCAN_II(RESCAN_II(RESCAN_II(arg))))
#define RESCAN_IV(arg)  RESCAN_III(RESCAN_III(RESCAN_III(RESCAN_III(arg))))
#define RESCAN_V(arg)   RESCAN_IV(RESCAN_IV(RESCAN_IV(RESCAN_IV(arg))))

#define XSTRINGIFY(...) #__VA_ARGS__
#define STRINGIFY(...) XSTRINGIFY(__VA_ARGS__)
#define LSTRINGIFY(...) CAT(L, XSTRINGIFY(__VA_ARGS__))
#define RSTRINGIFY(...) CAT(R, XSTRINGIFY(__raw__(__VA_ARGS__)__raw__))
#define U8STRINGIFY(...) CAT(u8, XSTRINGIFY(__VA_ARGS__))
#define U16STRINGIFY(...) CAT(u, XSTRINGIFY(__VA_ARGS__))
#define U32STRINGIFY(...) CAT(U, XSTRINGIFY(__VA_ARGS__))
#define USTRINGIFY(...) COMPILER_USTRINGIFY_VER(__VA_ARGS__)
#define COMPILER_USTRINGIFY_VER(...) EXPAND(TRICAT(U, COMPILER_UNICODE_VERSION, STRINGIFY)(__VA_ARGS__))

#endif //PROJECT3_TEST_CONFIG_FUNCTIONS_HPP
